# Generated by Django 3.0.2 on 2020-02-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_gnu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_gnu.College'),
        ),
    ]
