# Generated by Django 3.0.2 on 2020-03-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_gnu', '0002_auto_20200313_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gpio_pin',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (2, 2), (4, 4), (5, 5), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], null=True),
        ),
    ]
