# Generated by Django 3.0.2 on 2020-03-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_gnu', '0003_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='college',
            unique_together={('college_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('department_name', 'college')},
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_name', 'lab')},
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('lab_number', 'department')},
        ),
    ]
