# Generated by Django 3.0.2 on 2020-03-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_gnu', '0005_nodemcu'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='node_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
