# Generated by Django 3.0.2 on 2020-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_gnu', '0007_auto_20200307_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gpio_pin',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
    ]
