# Generated by Django 3.0.2 on 2020-03-10 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_gnu', '0008_auto_20200307_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='qr_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='collegeuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('lab_number', 'department', 'qr_code')},
        ),
    ]
